image: python:3.8

pipelines:
  branches:
    master: &shared
      - step:
          size: 2x
          name: build tag and push image
          caches:
            - pip
          script:
            - DIR="dnp3"
            - pip install awscli
            - aws configure set region us-east-1
            - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            - pip install docker-compose
            - pass=$(aws ecr get-login-password --region us-east-1)
            - docker login --username AWS --password $pass $API_TEST_ECR
            - docker-compose build
            - docker tag splight-grid-sim $API_TEST_ECR/splight-grid-sim
            - docker push $API_TEST_ECR/splight-grid-sim
          services:
            - docker
