version: "3.9"
services:
  dnp3-stage:
    image: dnp3-stage
    build:
      context: .
      dockerfile: ./dnp3/Dockerfile

  simulator:
    image: splight-grid-sim
    command: bash
    entrypoint: python3 ./network.py
    depends_on:
      - dnp3-stage
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/root/data/
    tty: true
    network_mode: "host"
