version: "3.9"
services:
  dnp3-stage:
    image: dnp3-stage
    build:
      context: .
      dockerfile: ./dnp3/Dockerfile

  c37118-stage:
    image: c37118-stage
    build:
      context: .
      dockerfile: ./c37118/Dockerfile

  iec60870-stage:
    image: iec60870-stage
    build:
      context: .
      dockerfile: ./iec60870/Dockerfile

  iec61850-stage:
    image: iec61850-stage
    build:
      context: .
      dockerfile: ./iec61850/Dockerfile

  electrical-simulator:
    image: splight-grid-sim
    command: bash
    entrypoint: python3 ./network.py
    depends_on:
      - dnp3-stage
      - c37118-stage
      - iec60870-stage
      - iec61850-stage
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/root/data/
    tty: true
    network_mode: "host"

  ftp-simulator:
    image: fauria/vsftpd
    volumes: 
      - '/ftp-data/:/home/vsftpd'
    network_mode: "host"
    environment:
      - FTP_USER=admin
      - FTP_PASS=admin
      - PASV_ADDRESS=192.168.50.201
    restart: always

  mqtt-broker:
      image: eclipse-mosquitto
      hostname: mosquitto
      ports:
        - "1883:1883"
      volumes: 
        - ./mqtt/mosquitto:/mosquitto/config
        
  mqtt-publisher:
    build: ./mqtt
    network_mode: host
