version: "3.9"
services:
  c37118:
    image: c37118
    build:
      context: .
      dockerfile: ./c37118/Dockerfile
    command: bash
    entrypoint: python3 /usr/bin/c37118
    volumes:
      - ./c37118/data:/root/data/
    tty: true
    network_mode: "host"

  