services:
  mqtt:
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./servers/mqtt:/mosquitto/config

  mqtt-device:
    tty: true
    restart: always
    build:
      context: ./devices/mqtt
    network_mode: host
    volumes:
      - ./data/mqtt/traces:/src/traces
    command:
      - python
      - /src/main.py
    environment:
      - LOG_LEVEL=INFO
