version: "3.9"
services:
  dnp3-stage:
    image: dnp3-stage
    build:
      context: .
      dockerfile: ./dnp3/Dockerfile

  c37118-stage:
    image: c37118-stage
    build:
      context: .
      dockerfile: ./c37118/Dockerfile

  iec60870-stage:
    image: iec60870-stage
    build:
      context: .
      dockerfile: ./iec60870/Dockerfile

  iec61850-stage:
    image: iec61850-stage
    build:
      context: .
      dockerfile: ./iec61850/Dockerfile

  simulator:
    image: splight-grid-sim
    command: bash
    entrypoint: python3 ./network.py
    depends_on:
      - dnp3-stage
      - c37118-stage
      - iec60870-stage
      - iec61850-stage
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/root/data/
    tty: true
    network_mode: "host"
