version: '3.1'
services:
  mqtt-broker:
      image: eclipse-mosquitto
      hostname: mosquitto
      ports:
        - "1883:1883"
      volumes: 
        - ./mosquitto:/mosquitto/config

  mqtt-publisher:
    build: .
    network_mode: host