LIB60870_HOME=../lib60870/lib60870-C

PROJECT_BINARY_NAME = iec60870
PROJECT_SOURCES = iec60870_custom_server.c

include $(LIB60870_HOME)/make/target_system.mk
include $(LIB60870_HOME)/make/stack_includes.mk

all:	libs $(PROJECT_BINARY_NAME)

include $(LIB60870_HOME)/make/common_targets.mk

libs:
	make -C $(LIB60870_HOME)


$(PROJECT_BINARY_NAME):	$(PROJECT_SOURCES) $(LIB_NAME)
	$(CC) $(CFLAGS) $(LDFLAGS) -g -o $(PROJECT_BINARY_NAME) $(PROJECT_SOURCES) $(INCLUDES) $(LIB_NAME) $(LDLIBS)

clean:
	rm -f $(PROJECT_BINARY_NAME)
