name: Deploy master branch

# on:
#   push:
#     branches:
#       - master

on:
  pull_request:
    types:
      [opened, synchronize]
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, SplightSIM]
    steps:
      - uses: actions/checkout@v3
      - name: Run container
        run: |
          sudo docker-compose build
          sudo docker-compose up -d
