name: Deploy manually

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage for sim to be deployed (options: integration-v4, production-v4, all)"
        required: true
        default: "integration-v4"

jobs:
  deploy-integration-v4:
    if: github.event.inputs.stage == 'integration-v4' || github.event.inputs.stage == 'all'
    name: Deploy integration v4
    runs-on:
      group: SplightSIM
      labels: [self-hosted, integration-v4]
    steps:
    - uses: actions/checkout@v4
    - name: Run integration v4 container
      run: |
        sudo docker-compose build
        sudo docker-compose up -d --force-recreate

  deploy-production-v4:
    if: github.event.inputs.stage == 'production-v4' || github.event.inputs.stage == 'all'
    name: Deploy production v4
    runs-on:
      group: SplightSIM
      labels: [self-hosted, v4]
    steps:
    - uses: actions/checkout@v4
    - name: Run production v4 container
      run: |
        sudo docker-compose build
        sudo docker-compose up -d --force-recreate
